# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'lesson_10_mainWidget.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *
from PySide2.QtCharts import QtCharts


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 638)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-10, 10, 781, 541))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_global = QWidget()
        self.tab_global.setObjectName(u"tab_global")
        self.tab_global.setEnabled(True)
        self.treeView = QTreeView(self.tab_global)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(20, 10, 191, 491))
        self.tabWidget.addTab(self.tab_global, "")
        self.tab_user = QWidget()
        self.tab_user.setObjectName(u"tab_user")
        self.listView = QListView(self.tab_user)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(20, 10, 191, 491))
        self.groupBox = QGroupBox(self.tab_user)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(220, 330, 551, 171))
        self.listView_2 = QListView(self.groupBox)
        self.listView_2.setObjectName(u"listView_2")
        self.listView_2.setGeometry(QRect(10, 30, 241, 131))
        self.listView_3 = QListView(self.groupBox)
        self.listView_3.setObjectName(u"listView_3")
        self.listView_3.setGeometry(QRect(300, 30, 241, 131))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(260, 30, 30, 30))
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(260, 60, 30, 30))
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(260, 100, 30, 30))
        self.pushButton_4 = QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(260, 130, 30, 30))
        self.groupBox_2 = QGroupBox(self.tab_user)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(220, 160, 551, 171))
        self.listView_4 = QListView(self.groupBox_2)
        self.listView_4.setObjectName(u"listView_4")
        self.listView_4.setGeometry(QRect(10, 30, 241, 131))
        self.listView_5 = QListView(self.groupBox_2)
        self.listView_5.setObjectName(u"listView_5")
        self.listView_5.setGeometry(QRect(300, 30, 241, 131))
        self.pushButton_5 = QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(260, 30, 30, 30))
        self.pushButton_6 = QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(260, 60, 30, 30))
        self.pushButton_7 = QPushButton(self.groupBox_2)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(260, 100, 30, 30))
        self.pushButton_8 = QPushButton(self.groupBox_2)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(260, 130, 30, 30))
        self.tabWidget.addTab(self.tab_user, "")
        self.tab_In = QWidget()
        self.tab_In.setObjectName(u"tab_In")
        self.listView_8 = QListView(self.tab_In)
        self.listView_8.setObjectName(u"listView_8")
        self.listView_8.setGeometry(QRect(20, 10, 201, 491))
        self.graphicsView_3 = QGraphicsView(self.tab_In)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(230, 10, 541, 491))
        self.tabWidget.addTab(self.tab_In, "")
        self.tab_Out = QWidget()
        self.tab_Out.setObjectName(u"tab_Out")
        self.listView_7 = QListView(self.tab_Out)
        self.listView_7.setObjectName(u"listView_7")
        self.listView_7.setGeometry(QRect(20, 10, 201, 491))
        self.graphicsView_2 = QGraphicsView(self.tab_Out)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(230, 10, 541, 491))
        self.tabWidget.addTab(self.tab_Out, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(20, 10, 181, 131))
        self.label = QLabel(self.groupBox_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 67, 17))
        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 60, 67, 17))
        self.label_3 = QLabel(self.groupBox_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 90, 67, 17))
        self.comboBox = QComboBox(self.groupBox_3)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(50, 30, 111, 25))
        self.comboBox_2 = QComboBox(self.groupBox_3)
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(50, 60, 111, 25))
        self.lineEdit = QLineEdit(self.groupBox_3)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(50, 90, 113, 25))
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(220, 30, 120, 80))
        self.groupBox_5 = QGroupBox(self.tab)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(410, 40, 120, 80))
        self.tabWidget.addTab(self.tab, "")
        self.btn_quit = QPushButton(self.centralwidget)
        self.btn_quit.setObjectName(u"btn_quit")
        self.btn_quit.setGeometry(QRect(700, 560, 89, 25))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_global), QCoreApplication.translate("MainWindow", u"Config", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Out", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u">>", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"<<", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"In", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u">>", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"<<", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_user), QCoreApplication.translate("MainWindow", u"User", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_In), QCoreApplication.translate("MainWindow", u"In", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Out), QCoreApplication.translate("MainWindow", u"Out", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Level", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"File", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Route", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"DNS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Misc", None))
        self.btn_quit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
    # retranslateUi

